---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    percona:
      encrypted_data_bag: percona
      encrypted_data_bag_secret_file: /etc/chef/encrypted_data_bag_secret


platforms:
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: orvsd
    run_list:
      - recipe[osl-mysql::orvsd]
  - name: server
    run_list:
      - recipe[osl-mysql::server]
  - name: mon
    provisioner: chef_zero
    run_list:
      - recipe[osl-mysql::mon]
  - name: server-sysctl
    run_list:
      - recipe[osl-mysql::server]
      - recipe[sysctl::apply]
