---
driver:
  flavor_ref: 'm1.medium'
provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    omnibus_updater:
      disabled: true
    percona:
      encrypted_data_bag: percona
      encrypted_data_bag_secret_file: "/etc/chef/encrypted_data_bag_secret"

suites:
  - name: orvsd
    run_list:
      - recipe[osl-mysql::orvsd]
  - name: server
    run_list:
      - recipe[osl-mysql::server]
  - name: mon
    provisioner: chef_zero
    run_list:
      - recipe[osl-mysql::mon]
  - name: backup
    run_list:
      - recipe[osl-mysql::backup]
  - name: xtrabackuprb
    run_list:
      - recipe[osl-mysql::xtrabackuprb]
