---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[osl-mysql::default]
    attributes:
  - name: orvsd
    run_list:
      - recipe[osl-mysql::orvsd]
  - name: server
    run_list:
      - recipe[osl-mysql::server]
