---
verifier:
  name: inspec
driver:
  flavor_ref: 'm1.medium'
provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    omnibus_updater:
      disabled: true
    percona:
      encrypted_data_bag: percona
      encrypted_data_bag_secret_file: "/etc/chef/encrypted_data_bag_secret"

suites:
  - name: server
    run_list:
      - recipe[osl-mysql::server]
    excludes:
      - centos-6
  - name: mon
    provisioner: chef_zero
    run_list:
      - recipe[osl-mysql::mon]
    excludes:
      - centos-6
  - name: backup
    run_list:
      - recipe[osl-mysql::backup]
  - name: xtrabackuprb
    run_list:
      - recipe[osl-mysql::xtrabackuprb]
  - name: client
    run_list:
      - recipe[osl-mysql::client]
  - name: client-percona
    run_list:
      - recipe[osl-mysql::client]
    attributes:
      osl-mysql:
        enable_percona_client: true
  - name: multi-node
    driver:
      name: terraform
      command_timeout: 1800
    provisioner: terraform
    verifier:
      name: terraform
      systems:
        - name: master
          backend: ssh
          hosts_output: master
          sudo: true
          user: centos
          controls:
            - all
            - master
          hostnames: master
        - name: slave
          backend: ssh
          hosts_output: slave
          sudo: true
          user: centos
          controls:
            - all
            - slave
          hostnames: slave
    excludes:
      - centos-6
